apiVersion : apps/v1
kind: Deployment
metadata:
  name: psb-registration 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psb-registration
  template:
    metadata:
      labels:
        app: psb-registration 
    spec:
      containers:
        - name: psb-registration 
          image: reproches.azurecr.io/psb-registration
          ports:
          - containerPort: 8084
